name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version1: ["3.8"]
        python-version2: ["3.9"]
        python-version3: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version1 }}
      - name: Display Python version 3.8
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import sys; print(sys.version)" > python_result.txt
        id: python38
        
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version2 }}
      - name: Display Python version 3.9
        run: | 
          python -c "import sys; print(sys.version)"
          python -c "import sys; print(sys.version)" > python_result.txt
        id: python39
        
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version3 }}
      - name: Display Python version 3.10
        run: | 
          python -c "import sys; print(sys.version)"
          python -c "import sys; print(sys.version)" > python_result.txt
        id: python310
        
      - name: Save as file
        run: |
          echo "${{ steps.python38.outputs.stdout }}" > python_result.txt
          echo "${{ steps.python39.outputs.stdout }}" > python_result.txt
          echo "${{ steps.python310.outputs.stdout }}" > python_result.txt
